//! Embeds skill and prompt markdown for crates.io (from `embed/` in the published crate).

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let embed = manifest_dir.join("embed");
    let fallback_root = manifest_dir.join("../..");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", embed.join("skills").display());
    println!("cargo:rerun-if-changed={}", embed.join("prompts").display());

    let mut out = String::from("// @generated by build.rs — do not edit\n");
    for (dir, const_name) in [
        ("driftlock", "SKILL_DRIFTLOCK"),
        ("driftlock-planner", "SKILL_PLANNER"),
        ("driftlock-worker", "SKILL_WORKER"),
        ("driftlock-reviewer", "SKILL_REVIEWER"),
        ("driftlock-maintainer", "SKILL_MAINTAINER"),
        ("driftlock-tdd", "SKILL_TDD"),
        ("driftlock-mcp-operator", "SKILL_MCP_OPERATOR"),
    ] {
        let path = resolve(&embed, &fallback_root, &format!("skills/{dir}/SKILL.md"));
        embed_file(&mut out, const_name, &path);
    }
    for (file, const_name) in [
        ("worker-start.md", "PROMPT_WORKER_START"),
        ("planner-extract-adr.md", "PROMPT_PLANNER_EXTRACT_ADR"),
        ("reviewer-gate.md", "PROMPT_REVIEWER_GATE"),
        ("conflict-review.md", "PROMPT_CONFLICT_REVIEW"),
        ("maintainer-refresh.md", "PROMPT_MAINTAINER_REFRESH"),
        ("agent-brief-template.md", "PROMPT_AGENT_BRIEF_TEMPLATE"),
    ] {
        let path = resolve(&embed, &fallback_root, &format!("prompts/{file}"));
        embed_file(&mut out, const_name, &path);
    }

    fs::write(out_dir.join("generated.rs"), out).expect("write generated.rs");
}

fn resolve(embed: &Path, fallback_root: &Path, rel: &str) -> PathBuf {
    let in_embed = embed.join(rel);
    if in_embed.exists() {
        in_embed
    } else {
        fallback_root.join(rel)
    }
}

fn embed_file(out: &mut String, const_name: &str, path: &Path) {
    let body = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    out.push_str(&format!("pub const {const_name}: &str = {body:?};\n"));
}
